---
# tasks file for config_ir_nsxt
- name: Connect to "{{ vcd.cell.primary.0.system_name }}" and get a token
  uri:
    url: https://{{ vcd.cell.primary.0.system_name }}/api/sessions
    method: POST
    status_code: 200
    validate_certs: no
    headers:
      Accept: application/*;version={{ vcd.api_version }}
    user: "{{ vcd.username }}@system"
    password: "{{ vcd.password }}"
    force_basic_auth: yes
  register: vcd_session

- include_tasks: nsx.yml
  loop:
    - "{{ nsx }}"