---
# tasks file for vcd_config_feature-flag
- name: Get feature flag from "{{ inventory_hostname }}"
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/cloudapi/1.0.0/featureFlags
    status_code: [200]
    method: GET
    headers:
      Accept: application/*;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
  register: vcd_feature_flags
  delegate_to: '{{ vcd.api_host }}'

- name: Loop feature flag
  include_tasks: config_feature-flag.yml
  loop: "{{ vcd.feature_flag }}"