---
# tasks file for vcd_config_import_certificates
- name: Get certificate from "{{ item.hostname }}"
  get_certificate:
    host: "{{ item.hostname }}"
    port: 443
  register: cert
  delegate_to: '{{ vcd.deployment.host }}'

- name: Add certificate "{{ item.hostname }}"
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/cloudapi/1.0.0/ssl/trustedCertificates
    status_code: [201, 400]
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
    body_format: json
    body:
      alias: "{{ item.hostname }}"
      certificate: "{{ cert.cert }}"
  register: result
  delegate_to: '{{ vcd.api_host }}'
