---
# tasks file for config_ir_vce
- name: Get certificate from "{{ item.0.hostname }}"
  get_certificate:
    host: "{{ item.0.hostname }}"
    port: 443
  register: cert

- name: Add certificate "{{ item.0.hostname }}"
  uri:
    validate_certs: false
    url: https://{{ vcd.cell.primary.0.system_name }}/cloudapi/1.0.0/ssl/trustedCertificates
    status_code: [201, 400]
    method: POST
    headers:
      Content-Type: application/json
      Accept: application/json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
    body_format: json
    body:
      alias: "{{ item.0.hostname }}"
      certificate: "{{ cert.cert }}"
  register: result

#- name: Fail if status code 400 and vCenter cert doesn't exist
#  fail:
#    msg: "vCenter certificate add fail"
#  when: result.status == 400 and 'Duplicate certificate' not in result.json.message#
