---
# tasks file for config_roles
- name: Test with a message
  vcd_roles:
    user: "{{ vcd.username }}"
    password: "{{ vcd.password }}"
    host: "{{ vcd.cell.primary.0.system_name }}"
    org: system
    api_version: "{{ vcd.api_version }}"
    verify_ssl_certs: False
    role_name: sample_role
    role_description: sample role
    role_rights:
        - "Catalog: Import Media from vSphere"
    state: "present"

#- include_tasks: generate_roles.yml
#  loop: "{{ vcd.roles }}"