---
# tasks file for config_placement-policy
- name: Get providerVdcs from "{{ inventory_hostname }}"
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/cloudapi/1.0.0/providerVdcs
    status_code: [200, 400]
    method: GET
    headers:
      Accept: application/json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
  register: providerVdcs
  delegate_to: '{{ vcd.api_host }}'

- debug:
    var: providerVdcs.json
    verbosity: 1

- name: Get namedVmGroupReferences from "{{ inventory_hostname }}"
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/api/admin/extension/namedVmGroupReferences
    status_code: [200, 400]
    method: GET
    headers:
      Accept: application/vnd.vmware.vcloud.query.references+json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
  register: namedVmGroupReferences
  delegate_to: '{{ vcd.api_host }}'

- debug:
    var: namedVmGroupReferences.json
    verbosity: 1



- name: Loop vm_placement_polices
  include_tasks: config_placement-policies.yml
  loop: "{{ vcd.vm_placement_policies }}"