---
# tasks file for config_cr_network-pools
- name: nsxtManagers
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/api/admin/extension/nsxtManagers
    status_code: [200, 400]
    method: GET
    headers:
      Accept: application/*+json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
  register: nsxtManagers

- include_tasks: network_pools.yml
  loop:
    "{{ nsxtManagers.json.nsxTManager }}"
  loop_control:
    loop_var: nsxTManager