---
# tasks file for config_cr_network-pools
- name: importableTransportZones
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/cloudapi/1.0.0/nsxTResources/importableTransportZones?filter=_context=={{ nsxTManager.id }}
    status_code: [200, 400]
    method: GET
    headers:
      Accept: application/json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
  register: importableTransportZones

- name: create networkpool
  uri:
    validate_certs: false
    url: https://{{ inventory_hostname }}/cloudapi/1.0.0/networkPools
    status_code: [202]
    method: POST
    headers:
      Accept: application/json;version={{ vcd.api_version }}
      Authorization: Bearer {{ vcd_session.x_vmware_vcloud_access_token }}
    body_format: json
    body:
      name: "{{ item.name }}"
      poolType: "{{ item.type }}"
      promiscuousMode: false
      backing:
        transportZoneRef:
          id: "{{ item.id }}"
          name: "{{ item.name }}"
        providerRef:
          id: "{{ nsxTManager.id }}"
          name: "{{ nsxTManager.name}}"
  loop:
    "{{ importableTransportZones.json | json_query('values[*]') }}"
  when: item.alreadyImported == false