---
# tasks file for config_cipher
- name: reset cipher
  shell: sh /opt/vmware/vcloud-director/bin/cell-management-tool ciphers -d

- name: configure cipher
  shell: sh /opt/vmware/vcloud-director/bin/cell-management-tool ciphers -d {{ vcd.cipher | join(',') }}