---
# tasks file for config_java
- name: Configure java heap size
  replace:
    path: /opt/vmware/vcloud-director/bin/vmware-vcd-cell-common
    regexp: 'JAVA_OPTS:--Xms\d{4}M -Xmx\d{4}M'
    replace: 'JAVA_OPTS:--Xms{{ vcd.java_opts.xms }}M -Xmx{{ vcd.java_opts.xmx }}M'
  register: result
  notify: Service vmware-vcd restart
  when:
    - 'vcd.java_opts.xms is defined'
    - 'vcd.java_opts.xmx is defined'